version: "3"
services:
  medusa-backend:
    build: ./medusa-backend
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    command: npm run docker:start
    volumes:
      - .:/medusa-backend/db
      - /medusa-backend/medusa/node_modules

  postgres:
    image: postgres:14
    ports:
      - "35432:5432"

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  medusa-admin:
    build: ./medusa-admin
    volumes:
      - ./medusa-admin/src:/app/medusa-admin/src # Links the source files to the running container
