version: "3"
services:
  backend:
    build:
      context: ./packages/medusa-backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    command: yarn start
    volumes:
      - .:/backend/db
      - /backend/medusa/node_modules
    env_file:
      - ./.env

  postgres:
    image: postgres:14
    ports:
      - "35432:5432"
    env_file:
      - ./.env

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    env_file:
      - ./.env

  admin:
    build:
      context: ./packages/medusa-admin
      dockerfile: Dockerfile
    volumes:
      - ./admin/src:/app/admin/src
    env_file:
      - ./.env
    ports:
      - "7000:7000"
