version: "3"
services:
  backend:
    image: medusa
    build:
      context: ./
      dockerfile: ./packages/medusa-backend/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    volumes:
      # - .:/app/db
      - /app
    env_file:
      - ./.env

  postgres:
    image: postgres:14
    ports:
      - "35432:5432"
    env_file:
      - ./.env

  redis:
    image: redis
    expose:
      - 6379
    env_file:
      - ./.env

  # admin:
  #   image: admin
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.admin
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "7000:80"
