version: "3"
services:
  app:
    build: ./medusa-backend
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    command: npm run docker:start
    volumes:
      - .:/app/db
      - /app/medusa/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  client:
    build: ./admin
    volumes:
      - ./admin/src:/app/admin/src # Links the source files to the running container
