services:
  # Gatsby Admin
  - type: web
    name: admin
    env: static
    branch: main
    buildCommand: yarn admin:build
    staticPUblishPath: packages/medusa-admin/public
    routes:
      - type: rewrite
        source: "/a/*"
        destination: /a
    domains:
      - admin.themontessoriwoodshop.com

  # Redis
  - type: pserv
    name: redis
    env: docker
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10

  # Medusa Backend
  - type: web
    name: medusa
    env: node
    branch: main
    scaling: autoScaling
    buildCommand: yarn backend:build
    startCommand: yarn backend:migrate && yarn backend:start
    envVars:
      - key: MEDUSA_PORT
        value: 9000
      - key: MEDUSA_ADMIN_CORS
        value: admin.themontessoriwoodshop.com
      - key: MEDUSA_STORE_CORS
        value: themontessoriwoodshop.com
      - key: MEDUSA_DATABASE_URL
        fromDatabase:
          name: Postgres
          property: connectionString
      - key: MEDUSA_REDIS_HOST
        fromService:
          name: redis
          type: pserv
          property: host
      - key: MEDUSA_REDIS_PORT
        fromService:
          name: redis
          type: pserv
          property: port
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false


# Postgres DB
databases:
  - name: postgres
    databaseName: woodshop
    plan: starter
    user: postgres
    region: oregon
    postgresMajorVersion: 14



    