services:
  # Redis
  - type: pserv
    name: redis
    env: docker
    plan: starter
    dockerfilePath: ./redis/Dockerfile
    dockerContext: ./redis/
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10

  # Medusa
  - type: web
    name: medusa
    env: node
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60
    buildCommand: yarn install && yarn workspace medusa-file-cloudflare-images build && yarn workspace medusa build
    startCommand: yarn workspace medusa migrate && yarn workspace medusa start
    plan: starter
    domains:
      - store.themontessoriwoodshop.com
    envVars:
      - key: MEDUSA_PORT
        value: 9000
      - key: MEDUSA_ADMIN_CORS
        value: https://admin.themontessoriwoodshop.com
      - key: MEDUSA_STORE_CORS
        value: https://themontessoriwoodshop.com
      - key: MEDUSA_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: MEDUSA_REDIS_HOST
        fromService:
          name: redis
          type: pserv
          property: host
      - key: MEDUSA_REDIS_PORT
        fromService:
          name: redis
          type: pserv
          property: port
      - fromGroup: auth-secrets

# Env Var Groups
envVarGroups:
  - name: auth-secrets
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false

# Postgres DB
databases:
  - name: postgres
    databaseName: woodshop
    plan: starter
    user: app_user
    region: oregon
    postgresMajorVersion: 14



    