services:
  # Gatsby Admin
  - type: web
    name: admin
    env: static
    buildCommand: --immutable --immutable-cache --check-cache && yarn admin:build
    staticPublishPath: packages/medusa-admin/public
    routes:
      - type: rewrite
        source: "/a/*"
        destination: /a
    domains:
      - admin.themontessoriwoodshop.com
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true

  # Redis
  - type: pserv
    name: redis
    env: docker
    dockerfilePath: ./redis/Dockerfile
    dockerContext: ./redis/
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10

  # Medusa Backend
  - type: web
    name: medusa
    env: node
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60
    buildCommand: --immutable --immutable-cache --check-cache && yarn backend:build
    startCommand: yarn backend:migrate && yarn backend:start
    envVars:
      - key: MEDUSA_PORT
        value: 9000
      - key: MEDUSA_ADMIN_CORS
        value: admin.themontessoriwoodshop.com
      - key: MEDUSA_STORE_CORS
        value: themontessoriwoodshop.com
      - key: MEDUSA_DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: MEDUSA_REDIS_HOST
        fromService:
          name: redis
          type: pserv
          property: host
      - key: MEDUSA_REDIS_PORT
        fromService:
          name: redis
          type: pserv
          property: port
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false


# Postgres DB
databases:
  - name: postgres
    databaseName: woodshop
    plan: starter
    user: app_user
    region: oregon
    postgresMajorVersion: 14



    