name = "woodshop"
type = "javascript"
usage_model = "unbound"
zone_id = "ebeb335a5410105683a9e7bc11251d1c" # no risk at exposing this
account_id = "68fa4421d84bfcddbd9311a7d57aa419" # no risk at exposing this
compatibility_date = "2021-11-30"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[vars]
MEDUSA_URL = "http://localhost:9000"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[env.develop]
name = "woodshop_dev"
route = "dev.themontessoriwoodshop.com/*"

[env.develop.vars]
MEDUSA_URL = "https://dev.store.themontessoriwoodshop.com"

[env.production]
name = "woodshop_prod"
route = "themontessoriwoodshop.com/*"

[env.production.vars]
MEDUSA_URL = "https://store.themontessoriwoodshop.com"





