name: Deployment to DEV

concurrency: 
  group: development
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test --if-present
      - name: Build & Deploy
        run: yarn deploy:dev
